[FIX] purchase{,_stock}: use gross price unit for price diff Because of taxes included in price, some bills may generate incorrect lines in the price difference account
To reproduce the issue:
(Need account_accountant)
1. Create a taxe T:
   - Amount > 0
   - Type: Purchases
   - Included in Price
2. Create a product category C:
   - Method: FIFO
   - Valuation: Automated
   - Price Difference Account: a new account
3. Create a product P
   - Storable
   - Categort C
   - Vendor Taxes T
   - Control Policy: On ordered quantities
4. Create and confirm a PO with 1 x P @ $1000 with T
5. Create and confirm the bill

Error: Some lines are generated in the price difference account
because of the unit price of P with/without the taxe

When comparing the PO unit price with the Bill unit price, we only
exclude the tax on one side, hence the difference.